### ISSUE TITLE
Add ability to filter files

### ISSUE THREAD

**Issue by akulmehta** [diggyk/fildir#2]
Currently fildir only filters folders. However, some folders are sometimes with many files. It would be great if fildir can filter files also. Maybe this can be enabled in some settings?

Really useful extension by the way - thanks.

**Comment by diggyk** [comment]
I'll look into it.  I think it should be doable.  Glad you like the extension!

**Comment by diggyk** [comment]
@akulmehta check out the pre-release version and see if that works for you.  I need to add actual unit tests but I hand verified.

**Comment by akulmehta** [comment]
@diggyk just tried it. It is not showing in the Filtered View. I think this is because the FilDir is adding a trailing `/` to the filename. Files should not have a trailing `/`

![image](https://user-images.githubusercontent.com/42812604/211060452-8f68ee52-9622-4701-95d8-635291a4b95b.png)

**Comment by diggyk** [comment]
Hmm. I thought I removed code to add the trailing slashes. Let me push a fix tonight (traveling at the moment)

**Comment by diggyk** [comment]
Is that file a symlink by any chance?  I can't repro this with the pre-release version of the extension.  I only add a trailing `/` when the filetype is `directory`.

**Comment by akulmehta** [comment]
I am not sure what you mean by symlink - it is just a regular file.

**Comment by diggyk** [comment]
Strange.  The other thing that may have happened is it added the trailing slash when refreshing and normalizing the configs before it switched to the pre-release version.  I can't repro this.  When I right click a file and create a new filter, it doesn't add the slash if it was a file as opposed to a directory.  I'll keep trying.

**Comment by akulmehta** [comment]
I just disabled the extension, enabled it again and then switched to pre-release and reloaded and now everything works including issue #3

**Comment by akulmehta** [comment]
@diggyk - since it is working now could you put the changes in the release version?

**Comment by diggyk** [comment]
Done!  I'm working on getting Intellisense to work, if possible.
